# Generated by Django 2.0.3 on 2018-03-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_Infomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(blank=True, choices=[('서울', 'SEL'), ('부산', 'PUS'), ('인천', 'ICN'), ('김포', 'GMP'), ('로마', 'ROM'), ('피렌체', 'FLR')], max_length=3, verbose_name='도시명')),
            ],
        ),
        migrations.CreateModel(
            name='TicketInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(verbose_name='출발날짜')),
                ('enddate', models.DateField(verbose_name='도착날짜')),
                ('price', models.CharField(max_length=200, verbose_name='가격')),
                ('arrivecity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrive', to='search_flight.City_Infomation', verbose_name='도착도시')),
                ('startcity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='search_flight.City_Infomation', verbose_name='출발도시')),
            ],
        ),
    ]
