# Generated by Django 2.0.3 on 2018-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startcity', models.CharField(blank=True, max_length=200, verbose_name='출발도시')),
                ('arrivecity', models.CharField(blank=True, max_length=200, verbose_name='도착도시')),
                ('startdate', models.DateField(verbose_name='출발날짜')),
                ('enddate', models.DateField(verbose_name='도착날짜')),
                ('price', models.CharField(max_length=200, verbose_name='가격')),
            ],
        ),
    ]
