# Generated by Django 2.0.3 on 2018-05-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goreturn', models.CharField(max_length=2, verbose_name='출발/도착 구분')),
                ('departure_date', models.DateTimeField(blank=True, verbose_name='출발날짜')),
                ('departure_duration', models.CharField(max_length=100, verbose_name='소요시간')),
                ('country', models.CharField(max_length=50, verbose_name='출발나라')),
                ('departure_city', models.CharField(max_length=50, verbose_name='출발도시')),
                ('arrival_city', models.CharField(max_length=50, verbose_name='도착도시')),
                ('flight_company', models.CharField(max_length=20, verbose_name='항공사명')),
                ('ticket_price', models.IntegerField(verbose_name='가격')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='환율')),
                ('fee_policy', models.CharField(blank=True, max_length=100, verbose_name='요금규정')),
                ('data_source', models.CharField(max_length=30, verbose_name='데이터 출처')),
                ('url_link', models.URLField(verbose_name='데이터 링크')),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제데이터여부')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modify_datetime', models.DateTimeField(auto_now_add=True, verbose_name='수정시간')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='설명')),
            ],
        ),
    ]
