# Generated by Django 2.0.3 on 2018-05-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdata',
            name='ticketID',
        ),
    ]
