# Generated by Django 2.0.3 on 2018-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdata',
            name='url_link',
        ),
        migrations.AlterField(
            model_name='ticketdata',
            name='departure_date',
            field=models.DateField(blank=True, verbose_name='출발날짜'),
        ),
    ]
