# Generated by Django 2.0.3 on 2018-05-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_ticketdata_ticketid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketdata',
            old_name='duration',
            new_name='flight_time',
        ),
    ]
