# Generated by Django 2.0.3 on 2018-05-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20180516_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdata',
            name='url_link',
            field=models.URLField(blank=True, verbose_name='웹페이지링크'),
        ),
    ]
