# Generated by Django 2.0.3 on 2018-06-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20180524_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdata',
            name='Leftseat',
            field=models.CharField(blank=True, max_length=30, verbose_name='잔여좌석'),
        ),
    ]
