# Generated by Django 2.0.3 on 2018-06-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20180608_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.CharField(max_length=40, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name='사용자 이름')),
                ('departure_date', models.DateField(verbose_name='출발날짜')),
                ('user_max_price', models.IntegerField(verbose_name='최대가격')),
            ],
        ),
    ]
