# Generated by Django 2.0.3 on 2018-06-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_mailcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcondition',
            name='destination_place',
            field=models.CharField(default=1, max_length=50, verbose_name='도착도시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailcondition',
            name='origin_place',
            field=models.CharField(default=1, max_length=50, verbose_name='출발도시'),
            preserve_default=False,
        ),
    ]
