# Generated by Django 2.0.3 on 2018-06-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20180628_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketdata',
            options={'ordering': ('departure_date', 'departure_datetime')},
        ),
    ]
