#docker build -t ec2-deploy.base Dokcerfile.base .

FROM        python:3.6.4-slim
MAINTAINER  devhsj@gmail.com


ENV         LANG C.UTF-8

RUN     apt-get -y update
RUN     apt-get -y dist-upgrade
RUN     apt-get -y install build-essential nginx supervisor

COPY    . /srv/ticket
COPY    .requirements /srv/.requirements

WORKDIR /srv
RUN     pip install --upgrade pip
RUN     apt-get install -y cron vim
RUN     pip install -r /srv/.requirements/production.txt