# Generated by Django 2.0.3 on 2018-07-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='ticket',
            new_name='tickets',
        ),
    ]
