# Generated by Django 2.0.3 on 2018-06-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20180629_1321'),
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiver',
            options={'ordering': ('departure_date',)},
        ),
        migrations.AddField(
            model_name='receiver',
            name='ticket',
            field=models.ManyToManyField(to='ticket.TicketData'),
        ),
    ]
