# Generated by Django 2.0.3 on 2018-07-09 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
        ('mail', '0002_auto_20180709_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='tickets',
        ),
        migrations.AddField(
            model_name='selectedticket',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Receiver'),
        ),
        migrations.AddField(
            model_name='selectedticket',
            name='ticket_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketData'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='ticket_lists',
            field=models.ManyToManyField(through='mail.SelectedTicket', to='ticket.TicketData'),
        ),
    ]
