# Generated by Django 2.0.3 on 2018-07-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20180709_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedticket',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_datas', to='mail.Receiver', verbose_name='receiver'),
        ),
        migrations.AlterField(
            model_name='selectedticket',
            name='ticket_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='ticket.TicketData', verbose_name='ticket_data'),
        ),
    ]
